type ContentfulAnotherTestContent implements Node {
	name: String
	# image: Asset		# needs human revision
}
type ContentfulComponentAuthor implements Node {
	internalName: String!
	name: String!
	# avatar: Asset		# needs human revision
}
type ContentfulComponentRichImage implements Node {
	internalName: String!
	# image: Asset!		# needs human revision
	caption: String
	fullWidth: Boolean
}
type ContentfulComponentSeo implements Node {
	internalName: String!
	pageTitle: String!
	pageDescription: String
	canonicalUrl: String
	nofollow: Boolean!
	noindex: Boolean!
	# shareImages: [Asset]		# needs human revision
}
type ContentfulFakePost implements Node {
	title: String
	description: String
	relatedThings: [ContentfulAnotherTestContent]
	relatedThing: ContentfulAnotherTestContent
}
type ContentfulPageBlogPost implements Node {
	internalName: String!
	# seoFields: IComponentSeo		# needs human revision
	slug: String!
	# author: IComponentAuthor		# needs human revision
	publishedDate: String!
	title: String!
	shortDescription: String
	# featuredImage: Asset!		# needs human revision
	# content: Document!		# needs human revision
	# relatedBlogPosts: [IPageBlogPost]		# needs human revision
}
type ContentfulPageLanding implements Node {
	internalName: String!
	# seoFields: IComponentSeo		# needs human revision
	# featuredBlogPost: IPageBlogPost		# needs human revision
}